sudo: false

language: php
dist: precise

notifications:
  email:
    on_success: never
    on_failure: change
  slack: bsf-bots:RDGCoMDDxnlCvnUfvhq8pQ36

cache:
  - composer
  - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
      env: WP_TRAVISCI=phpcs

before_script:
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer install
    fi

script:
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      vendor/bin/phpcs
    fi
